### ISSUE TITLE
create a tensorflow 2.0 version of chapter 13 to 16?

### ISSUE THREAD

**Issue by yasserius-ml** [rasbt/python-machine-learning-book-2nd-edition#118]
new learners might benefit from using the latest stable release, especially because of tf 2.0's simpler syntax.

**Comment by rasbt** [comment]
Hi there,

We use Tf 2.0 in the 3rd edition -- we decided against changing the code here for the 2nd edition since it won't match the text in the book anymore and would be confusing. The code notebooks for the third edition are available here: https://github.com/rasbt/python-machine-learning-book-3rd-edition

I will be closing this issue because I think the 3rd edition addresses it, but please let me know if you have any questions.
