### ISSUE TITLE
divide by zero encountered in log in chapter 12

### ISSUE THREAD

**Issue by cristinasegalin** [rasbt/python-machine-learning-book-2nd-edition#49]
Hello, I tried to use this implementation of MLP on my data but every time at the 4th epoch I get an error when computing term2 in the cost functions, meaning `divide by zero encountered in log`
How can I get around this problem? Would it be wrong to add an eps like `term2 = (1. - y_enc) * (np.log(1. - output+np.spacing(1)))`  or clipping the `output` to a min value?
Thank you

**Comment by rasbt** [comment]
Hi, 

I think this issue occurs due to numerical instabilities in Python & NumPy for the current implementation. I.e., the code tries to evaluate log(0), which is undefined. This is probably happening in the following calculation

```python
term2 = (1. - y_enc) * np.log(1. - output)
```

where `np.log(1. - 1.)` causes the error. Mathematically, `output` can never be exactly 1, because mathematically, the range of the logistic function (which computes `output`) is (0, 1) and not [0, 1].

One reason this might happen is that the network weights get really large due to exploding gradient problems. If you haven't standardized the your input dataset, standardizing or normalizing it may help (and be recommended in any case).

If this doesn't help, you can subtract a small constant from "output". For example, you can rewrite 

```python
        term2 = (1. - y_enc) * np.log(1. - output)
```

as

        term2 = (1. - y_enc) * np.log(1. - output + 1e-05)

or

        term2 = (1. - y_enc) * np.log(1. - (output + 1e-05))

Hope that solves the issue :)

**Comment by cristinasegalin** [comment]
Hi,

yes my data is already standardized.

I added a really small value and if using a large number of epochs it 
was working. I tried now with  a lower number of epoch and it doesn't 
work anymore.

This is weird

**Comment by rasbt** [comment]
I think in that case you may encounter the same issue also in the `term1` calculation. So in that case, modifying this as well might hopefully solve the issue. I.e.,

	term1 = -y_enc * (np.log(output + 1e-5))
	term2 = (1. - y_enc) * np.log(1. - output + 1e-5)

Let me know if that works :)

**Comment by cristinasegalin** [comment]
Seems working with this fix.

Thanks for the help and thanks for the really interesting and well 
documented code and book. It's really helping me to understand how to 
use Tensorflow as well.

**Comment by rasbt** [comment]
Cool, I am happy to hear that it's working! Also thanks for the note about the code & the book, that's very motivating to hear :).

PS: I should add a note about this to the code files. I am currently a bit busy but I will leave this issue open as a reminder to myself
