### ISSUE TITLE
 Chapter 10. Predicting Continuous Target Variables with Regression Analysis  

### ISSUE THREAD

**Issue by krishnamohan-seelam** [rasbt/python-machine-learning-book-2nd-edition#55]
In the section Dealing with nonlinear relationships using random forests
Unfortunately, there is now a universal approach for dealing with non-randomness in residual plots, and it requires experimentation

I am sort of confused with the above line in the book ,is it  "no" instead of now .

**Comment by dwoodlock** [comment]
Instead of "Unfortunately, there is now a universal approach for dealing with non-randomness in residual plots, and it requires experimentation."

I believe you want: "Unfortunately, there is not a universal approach for dealing with non-randomness in residual plots, and it requires experimentation."

**Comment by rasbt** [comment]
Sorry about the confusion, and @dwoodlock is correct, it should be "not" in this context, thanks! I just added it to the errata.
