### ISSUE TITLE
Iris dataset (Without Connection)

### ISSUE THREAD

**Issue by hectormtc** [rasbt/python-machine-learning-book-2nd-edition#69]
When you don't have internet and you are going to use the file directly from the same directory, for the code to run correctly you have to change the header of the file declaration

**df = pd.read_csv('iris.csv', header=None) #Problem**

to:

**df = pd.read_csv('iris.csv', header='infer') #ProblemFixing**

**Comment by rasbt** [comment]
Thanks for the note! Maybe I ask which chapter you are referring to? Maybe I am mixing something up, but I remember that I put the exact same `iris.data` (without the header) in the chapter's directory that should also work with `header=None`. Just wondering where you found the `'iris.csv'`

**Comment by rasbt** [comment]
Thanks! Just checked it out, but for me, I am actually getting the opposite problem because the iris.data file doesn't have a header. With `header='infer'`, pandas reads the file incorrectly:

`header=None`:

![screen shot 2018-04-27 at 10 37 30 am](https://user-images.githubusercontent.com/5618407/39368283-2cdcf8fe-4a07-11e8-8b87-31d1e6975dfc.png)

`header='infer'`

![screen shot 2018-04-27 at 10 37 41 am](https://user-images.githubusercontent.com/5618407/39368285-2f0375a4-4a07-11e8-871c-06a6cf973dbe.png)
