### ISSUE TITLE
License for image reuse

### ISSUE THREAD

**Issue by agitter** [rasbt/python-machine-learning-book-2nd-edition#74]
The images you created for this book are wonderful illustrations of machine learning concepts.  What license is applicable to the images?  Would it be acceptable to reuse your images in a presentation, blog post, GitHub guide, etc.?  If so, how would you like to be attributed?

I see the code is MIT-licensed but wanted to know whether that applies to the other content as well.

**Comment by rasbt** [comment]
Glad to hear that you find the figures useful! 

The situation is the following: Packt is ok with sharing the code and figures in the GitHub repo under the OSS (here: MIT) license as is. However, like you pointed out, an MIT license probably doesn't apply "artistic work" even though it's in/part of a "code notebook."

So in this case, given the general US guidelines/laws, the copyright would essentially be with me because I created and uploaded these figures prior to writing the second edition. For other book content, Packt would have the copyright.

To keep a long story short, from my side, I have nothing against using some of the figures in blog posts, presentations, and GitHub guides for non-commercial purposes.

Attribution-wise, maybe the following would be best:

Image source: <URL>. S. Raschka and V. Mirjalili, Python Machine Learning (2nd Ed.)

So, with the URL reference, it's then also clear that it wasn't copied from the book but from this GitHub repo but also appears in the book.

**Comment by rasbt** [comment]
I should mention that @vmirly created most of the the figures for Ch 14, 15, 16. CC'ing him here to hear his opinion as well.

**Comment by vmirly** [comment]
Cool! I am happy to see the figures are useful! 

Yes, in my opinion, reusing the figures as is in other works like presentations, blog-posts, ... is fine with proper attribution to the book like what @rasbt mentioned.

**Comment by agitter** [comment]
Excellent, thanks for the detailed explanation and permission to reuse your images with attribution.  I'll follow the format you specified above.
