### ISSUE TITLE
Logistic Regression convergence issue pg:199

### ISSUE THREAD

**Issue by sameervk** [rasbt/python-machine-learning-book-2nd-edition#88]
The logistic regression estimator (initialized on pg:197) of the pipeline failed to converge for the validation_curve object on pg:199 using the model's default solver, which is 'lbfgs', and so the plot was different from the one in the book. When I changed it to 'liblinear', there was no such error and the plot was replicated.
Also, I have not gone through your book completely yet but do you mention about the significance of choosing the right solvers? How important is it? Thank you.

**Comment by rasbt** [comment]
Thanks for the comment. I will make a note to change it if should make a new edition of the book one day. In older scikit-learn versions (pre 0.20.0), liblinear was actually the default so I never ran into that problem in that particular code example (https://scikit-learn.org/0.17/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression)

> Also, I have not gone through your book completely yet but do you mention about the significance of choosing the right solvers? How important is it? Thank you.

I felt like this was out of the scope for the book since it would require a lot of background in optimization theory and would be more like a book about scipy rather than scikit-learn then. In general I would say liblinear is nice and fast (not sure if I remember correctly, but the LIBLINEAR library does regularize the bias as well, so results may a be bit different compared to lbfgs and newton-cg, which is basically a quasi-Newton vs a Newton method. 


- https://en.wikipedia.org/wiki/Newton%27s_method_in_optimization
- https://en.wikipedia.org/wiki/Quasi-Newton_method

In case you want to play around with these, the respective scipy functions being used are

- https://docs.scipy.org/doc/scipy-0.18.1/reference/optimize.minimize-lbfgsb.html#optimize-minimize-lbfgsb
- https://docs.scipy.org/doc/scipy-0.18.1/reference/optimize.minimize-newtoncg.html

**Comment by sameervk** [comment]
Ok, thank you.
