### ISSUE TITLE
error in chapter 5, p162

### ISSUE THREAD

**Issue by mzakariaCERN** [rasbt/python-machine-learning-book-2nd-edition#92]
I think the output for the W matrix is wrong. Here is what i got:
Matrix W:
 [[-0.2406 -0.0834]
 [-0.3537 -0.1577]
 [-0.0168  0.0908]
 [ 0.1532 -0.2698]
 [ 0.1532 -0.2698]
 [-0.4775  0.3745]
 [ 0.3644  0.2362]
 [-0.3711 -0.2667]
 [-0.3711 -0.2667]
 [-0.236   0.3187]
 [-0.1565 -0.1489]
 [-0.1565 -0.1489]
 [-0.1584  0.2568]]

**Comment by rasbt** [comment]
Thanks for your note! Hm, that's weird, I still get the same if I rerun that environment. May I ask which numpy version you are using?

**Comment by mzakariaCERN** [comment]
Hello! 
`
import numpy
numpy.version.version 
`

gives:
'1.14.2'

It is odd that i am getting the right eigen values, but not the eigen vectors! I have my notebook here (I like to do type the code from the book)
https://github.com/mzakariaCERN/FunWithPython/tree/master/4_PCA

**Comment by rasbt** [comment]
Hm. I just reran the code in NumPy 0.14.5 and 0.14.6 and get the same results as in chapter 5. However, when I use numpy 1.15.4 the eigenvectors look slightly differently:

NumPy 0.14:

```
Matrix W:
 [[-0.13724218  0.50303478]
 [ 0.24724326  0.16487119]
 [-0.02545159  0.24456476]
 [ 0.20694508 -0.11352904]
 [-0.15436582  0.28974518]
 [-0.39376952  0.05080104]
 [-0.41735106 -0.02287338]
 [ 0.30572896  0.09048885]
 [-0.30668347  0.00835233]
 [ 0.07554066  0.54977581]
 [-0.32613263 -0.20716433]
 [-0.36861022 -0.24902536]
 [-0.29669651  0.38022942]]
```

NumPy 0.15.6:

```
Matrix W:
 [[ 0.1481 -0.4092]
 [-0.0908 -0.1577]
 [ 0.0168 -0.3537]
 [-0.1484  0.3223]
 [ 0.0163 -0.0817]
 [-0.1913  0.0842]
 [ 0.7338  0.2823]
 [ 0.075  -0.0102]
 [-0.0018  0.0907]
 [-0.294  -0.2152]
 [ 0.0328  0.2747]
 [ 0.3547 -0.0124]
 [ 0.3915 -0.5958]]
```

When I look at the projections though, they still look reasonable:

PCA: 

![screen shot 2018-12-16 at 12 35 53 am](https://user-images.githubusercontent.com/5618407/50050779-aac5e300-00ca-11e9-9581-248ae8bcdf91.png)

LDA:

![screen shot 2018-12-16 at 12 36 00 am](https://user-images.githubusercontent.com/5618407/50050780-ae596a00-00ca-11e9-85d9-bb0498bcc55a.png)

My guess the change is due to some improvements in NumPy, but you should still get a good clustering/seperation. Have you tried to run the Jupyter notebook on your machine without making changes to the code? Maybe there's a chance that you accidentally executed some code in a different order or made some typo when typing the code directly from the book

**Comment by mzakariaCERN** [comment]
Found the problem. Mea Culpa!
